apiVersion: v1
kind: ServiceAccount
metadata:
  name: homeassistant-kubernetes-integration
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: homeassistant-kubernetes-integration
    app.kubernetes.io/component: rbac
