{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rbac.name" . }}
  labels:
    {{- include "rbac.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rbac.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "rbac.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
