{{- if .Values.tokenSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rbac.name" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rbac.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "rbac.name" . }}
type: kubernetes.io/service-account-token
{{- end }}
