apiVersion: v1
kind: Secret
metadata:
  name: homeassistant-kubernetes-integration-token
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: homeassistant-kubernetes-integration
    app.kubernetes.io/component: rbac
  annotations:
    kubernetes.io/service-account.name: homeassistant-kubernetes-integration
type: kubernetes.io/service-account-token
